name: aavishkarapp
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.5.19
  firebase_core: ^0.2.5
  firebase_database: ^1.0.4
  firebase_storage: ^1.0.2
  url_launcher: ^3.0.3
  flutter_webview_plugin: ^0.2.1+2
  flutter_facebook_login:
  cached_network_image: ^0.4.2
  firebase_messaging: ^2.0.0
  map_view:
  google_sign_in:
  crypto: ^2.0.3
  carousel_slider:
  flutter_swiper:
  barcode_scan: ^0.0.7
  intl: ^0.15.7
  palette_generator: ^0.1.0
  path_provider:
  spritewidget: ^0.9.17
  dynamic_theme:
    git:
      url: git://github.com/Norbert515/dynamic_theme.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.6.1


flutter_icons:
    android: "Aavishkar 2.0"
    ios: "Aavishkar 2.0"
    image_path: "images/logo.png"
    image_path_android: "images/logo.png"
    image_path_ios: "images/logo.png"
    adaptive_icon_background: "#FFFAFAFA"
    adaptive_icon_foreground: "images/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

# flutter:
#   fonts:
#    - family:  MyFlutterApp
#      fonts:
#       - asset: fonts/MyFlutterApp.ttf
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: CustomFonts
      fonts:
       - asset: lib/util/fonts/fonts/CustomFonts.ttf
    - family: WhatsappIcon
      fonts:
       - asset: lib/util/fonts/whatsappicon/whatsappiconfonts/Whatsappicon.ttf

    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Medium.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/events.png
    - images/Contributors/
    - images/Contact Us/
    - images/loader.svg
    - images/logo.png
    - images/login.jpg
    - images/imageplaceholder.png
    - images/imageplaceholder2.png
    - assets/nebula.png
    - assets/sprites.json
    - assets/sprites.png
    - assets/starfield.png
    - assets/game_ui.png
    - assets/game_ui.json
    - assets/ui_bg_top.png
    - assets/ui_bg_top_tabs.png
    - assets/ui_bg_bottom.png
    - assets/ui_popup.png
    - assets/music_game.mp3
    - assets/music_boss.mp3
    - assets/music_intro.mp3
    - assets/explosion_0.wav
    - assets/explosion_1.wav
    - assets/explosion_2.wav
    - assets/explosion_boss.wav
    - assets/explosion_player.wav
    - assets/laser.wav
    - assets/hit.wav
    - assets/levelup.wav
    - assets/pickup_0.wav
    - assets/pickup_1.wav
    - assets/pickup_2.wav
    - assets/pickup_powerup.wav
    - assets/click.wav
    - assets/buy_upgrade.wav
    - fonts/Orbitron-Medium.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
